read_news:
  description: >
    {sentence}후 대한민국의 거시경제를 분석해줘
  expected_output: >
    대한민국의 거시경제 상황은 좋은 상황이다.
    대한민국의 거시경제 상황은 나쁜 상황이다.
    대한민국의 거시경제 상황은 보통 상황이다.
    대한민국의 거시경제 상황은 좋지 않은 상황이다.
    대한민국의 거시경제 상황은 좋지 않은 상황이다.
  agent: news_reader